version: 0.0 
os: linux 
files:
  - source: /
    destiantion: /home/ec2-user/express-app 
hook:
   ApplicationStop:
     - location: script/application_stop.sh
       timeout: 300
       runas: ec2-user 
   BeforeInstall: 
     - location: scripts/before_install.sh 
       timeout: 300 
       runas: ec2-user 
   ApplicationStart:
     - location: scripts/application_start.sh

